"""Outcome tests for the Rydberg CZ phase-noise infidelity task.

Grades the numeric deliverable:

  /root/gate_infidelity.csv   200 rows x 2 cols, no header:
                              Rabi frequency Omega/2pi [MHz], CZ gate infidelity

plus a presence check on the companion paper draft /root/paper.pdf. Its
*content* is graded by the rubric in verifier/rubric.json, where a judge agent
can assess whether the figures are legible and internally consistent with the
agent's stated conventions — something a numeric assertion cannot do fairly,
since several phase-noise conventions are defensible. What is asserted here is
only that the file was delivered and is a PDF, so a run that never produced the
deliverable cannot still report a reward of 1.0.

The infidelity band comes from reference_bounds.json, generated by the oracle.
It brackets the two defensible answers to the open question the measurement
leaves — what the PSD does above the 8 MHz endpoint — so an agent that picks
either extreme, or anything sensible in between, passes; an agent that gets the
factor-of-4 frequency doubling, the SSB-to-frequency-noise conversion, or the
FRT response function wrong falls outside it.

Tests check the result, never the route taken to it.
"""

import json
import pathlib

import numpy as np
import pytest

CSV = pathlib.Path("/root/gate_infidelity.csv")
PAPER = pathlib.Path("/root/paper.pdf")
BOUNDS = pathlib.Path(__file__).with_name("reference_bounds.json")

N_ROWS = 200
RABI_MIN_MHZ = 1.0
RABI_MAX_MHZ = 10.0


@pytest.fixture(scope="module")
def table():
    """The agent's CSV as an (N, 2) float array."""
    if not CSV.is_file():
        pytest.fail(f"{CSV} was not produced")
    try:
        arr = np.loadtxt(CSV, delimiter=",")
    except ValueError as exc:
        pytest.fail(
            f"{CSV} is not a plain two-column numeric CSV — the prompt asks for "
            f"no column headers. Parse error: {exc}"
        )
    return np.atleast_2d(arr)


@pytest.fixture(scope="module")
def bounds():
    with BOUNDS.open() as fh:
        data = json.load(fh)
    return (np.array(data["rabi_MHz"]),
            np.array(data["eps_lo"]),
            np.array(data["eps_hi"]))


def test_csv_shape_and_no_header(table):
    """200 rows, 2 columns, numeric throughout."""
    assert table.ndim == 2 and table.shape[1] == 2, (
        f"expected 2 columns, got shape {table.shape}"
    )
    assert table.shape[0] == N_ROWS, (
        f"expected {N_ROWS} sample points, got {table.shape[0]}"
    )
    assert np.isfinite(table).all(), "CSV contains NaN or inf"


def test_rabi_frequency_grid(table):
    """Column 1 samples Omega/2pi over 1-10 MHz inclusive, strictly increasing."""
    rabi = table[:, 0]
    assert np.all(np.diff(rabi) > 0), "column 1 is not strictly increasing"
    assert rabi[0] == pytest.approx(RABI_MIN_MHZ, abs=1e-6), (
        f"grid starts at {rabi[0]} MHz, expected {RABI_MIN_MHZ} MHz — check the "
        "units: column 1 must be Omega/2pi in MHz"
    )
    assert rabi[-1] == pytest.approx(RABI_MAX_MHZ, abs=1e-6), (
        f"grid ends at {rabi[-1]} MHz, expected {RABI_MAX_MHZ} MHz"
    )


def test_infidelity_is_a_physical_probability(table):
    """Infidelity is a small positive number, and not a constant."""
    eps = table[:, 1]
    assert np.all(eps > 0), "infidelity must be strictly positive"
    assert np.all(eps < 1), "infidelity must be below 1"
    assert eps.std() / eps.mean() > 0.1, (
        "infidelity is essentially constant across 1-10 MHz; it must vary with "
        "Rabi frequency"
    )


def test_infidelity_decreases_with_rabi_frequency(table):
    """Faster gates integrate less low-frequency noise, so eps falls with Omega."""
    rabi, eps = table[:, 0], table[:, 1]
    assert eps[0] > eps[-1], (
        f"infidelity rises from {eps[0]:.3e} at {rabi[0]:.2f} MHz to "
        f"{eps[-1]:.3e} at {rabi[-1]:.2f} MHz; the FRT response narrows as "
        "Omega grows, so it must fall"
    )
    # allow local wiggle from a noisy measured PSD, but the trend must be clean
    rises = np.sum(np.diff(eps) > 0)
    assert rises < 0.1 * len(eps), (
        f"{rises} of {len(eps) - 1} steps increase — the curve is not monotonic "
        "enough to be a converged integral"
    )


def test_infidelity_matches_measured_noise_bracket(table, bounds):
    """The core physics check.

    Compares against the band spanned by the two defensible high-frequency
    extrapolations, widened 20% each side. Catches the factor-of-4 doubling
    error, SSB/frequency-noise conversion slips, and a wrong response function.
    """
    rabi, eps = table[:, 0], table[:, 1]
    ref_rabi, lo, hi = bounds
    lo_i = np.interp(rabi, ref_rabi, lo)
    hi_i = np.interp(rabi, ref_rabi, hi)

    below = eps < lo_i
    above = eps > hi_i
    bad = below | above
    if bad.any():
        mid = (lo_i + hi_i) / 2
        j = int(np.argmax(np.abs(np.log(eps / mid))))
        pytest.fail(
            f"{bad.sum()} of {len(eps)} points fall outside the accepted band "
            f"({below.sum()} too low, {above.sum()} too high). Worst at "
            f"Omega/2pi = {rabi[j]:.2f} MHz: reported {eps[j]:.4e}, accepted "
            f"[{lo_i[j]:.4e}, {hi_i[j]:.4e}], off by a factor of "
            f"{eps[j] / mid[j]:.2f}."
        )


def test_high_omega_scaling_reflects_a_flat_psd(table):
    """Shape check, independent of the magnitude check above.

    A PSD that rolls off inside the measurement band gives eps ~ 1/Omega^2.
    This laser's PSD is still flat at the 8 MHz endpoint, so the true slope
    over 5-10 MHz is shallower: about -1.5 for a mid-range extrapolation and
    -1.4 for the fully pessimistic one.

    The window is deliberately wide enough to admit the hard-truncated integral
    (slope -2.04), because truncation is one of the two defensible readings of
    the data and the magnitude test already accepts it. Whether the agent
    *states* that its high-Omega scaling is a cutoff artifact rather than real
    physics is graded by the bandwidth_caveat item in rubric.json, not here.

    What this catches is a wrong response function or a mis-scaled frequency
    axis: those distort the shape of the curve, not just its size.
    """
    rabi, eps = table[:, 0], table[:, 1]
    hi = rabi >= 5.0
    slope = np.polyfit(np.log(rabi[hi]), np.log(eps[hi]), 1)[0]
    assert -2.30 < slope < -0.80, (
        f"log-log slope over 5-10 MHz is {slope:.2f}, outside the physically "
        "reachable range for this measured PSD. Between 1/Omega (flat noise "
        "spectrum) and 1/Omega^2 (spectrum decaying inside the band) is "
        "expected; anything outside points to a wrong fidelity response "
        "function or a frequency-axis scaling error."
    )


def test_paper_pdf_was_delivered():
    """The write-up exists and is a PDF.

    Deliberately minimal. Whether the paper is any good — whether its figures
    match its stated conventions, whether the discussion confronts the
    measurement bandwidth — is the rubric's job, and a text-extraction
    assertion would grade formatting rather than physics. This only catches a
    deliverable that is missing, empty, or not actually a PDF.
    """
    if not PAPER.is_file():
        pytest.fail(f"{PAPER} was not produced")

    size = PAPER.stat().st_size
    assert size > 1024, f"{PAPER} is only {size} bytes; it holds no document"

    with PAPER.open("rb") as fh:
        header = fh.read(5)
        fh.seek(max(0, size - 2048))
        trailer = fh.read()

    assert header == b"%PDF-", (
        f"{PAPER} does not start with the PDF magic bytes (got {header!r}); "
        "the deliverable must be a PDF, not a renamed file of another format"
    )
    assert b"%%EOF" in trailer, (
        f"{PAPER} has no %%EOF marker near the end of the file; it looks "
        "truncated or was never finished being written"
    )
